security:
    providers:
      in_memory:
          memory:
              users:
                  user:
                      password: user
                      roles: 'ROLE_USER'
                  admin:
                      password: admin
                      roles: 'ROLE_ADMIN'
                  matt:
                      password: smith
                      roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
                login_path: login
                check_path: login

            logout:
                path:   /logout
                target: /
